"""Golden-file tests for the full ISO 19115-3 harvester pipeline.

Tests the complete transformation from XML to a CKAN-ready package dict:

    XML
    → ISODocument.read_values()
    → WAFHarvesterISO19115_3.get_package_dict()

Fixture files
-------------
- ``tests/fixtures/iso19115_3/00-xml/<name>.xml``          — input XML
- ``tests/fixtures/iso19115_3/01-ckan-package/<name>.json`` — expected package dict

The expected JSON may be a raw production ``package_show`` API response.
Fields generated by CKAN's database layer or by post-harvest enrichment
services are stripped before comparison using ``_SKIP_FIELDS``.

Workflow
--------
1. Add an ISO 19115-3 XML file to ``00-xml/``.
2. Run ``pytest`` — if no package JSON exists, one is generated from the
   current pipeline output and the test is skipped.
3. Review/edit the generated JSON in ``01-ckan-package/<name>.json``.
4. Re-run — test now asserts pipeline output == stored JSON.

Regenerate all golden files after intentional pipeline changes::

    pytest --regenerate-fixtures
"""

import json
import logging
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest
from lxml import etree

from ckanext.cioos_harvest.harvesters.waf import WAFHarvesterISO19115_3
from ckanext.cioos_harvest.model.iso19115_3 import ISODocument

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_TESTS_DIR = Path(__file__).parent
_FIXTURES_DIR = _TESTS_DIR / "fixtures" / "iso19115_3"
_XML_DIR = _FIXTURES_DIR / "00-xml"
_JSON_DIR = _FIXTURES_DIR / "01-ckan-package"

# ISO 19115-3 metadata namespace (used for root-element validation)
_MDB_NS = "http://standards.iso.org/iso/19115/-3/mdb/2.0"

# ---------------------------------------------------------------------------
# Fields excluded from comparison
# ---------------------------------------------------------------------------

# These fields appear in production package_show responses but are created by
# CKAN's database layer or by post-harvest enrichment services, never by the
# XML parsing + package-dict transformation that we are testing here.
_SKIP_FIELDS = frozenset(
    {
        # --- CKAN database records ---
        "creator_user_id",
        "num_tags",
        "isopen",
        "groups",
        "organization",
        "owner_org",
        "state",
        "type",
        "private",
        "relationships_as_object",
        "relationships_as_subject",
        # --- Post-harvest enrichment (translation service, CIOOS registry) ---
        "harvest_document_content",
        "xml_location_url",
        "included_in_data_catalogue",
        # --- Fields populated by CIOOS post-harvest scripts, not the parser ---
        "datacentre",
        # --- Standard CKAN author / maintainer (not mapped from ISO 19115-3) ---
        "author",
        "author_email",
        "maintainer",
        "maintainer_email",
        "url",
    }
)

# Extras keys added by ckanext-harvest infrastructure, post-harvest scripts,
# or database triggers — never by the XML-parsing + package-dict pipeline.
_EXTRAS_SKIP_KEYS = frozenset(
    {
        # --- ckanext-harvest infrastructure ---
        "h_job_id",
        "h_object_id",
        "h_source_id",
        "h_source_title",
        "h_source_url",
        "harvest_object_id",
        "harvest_source_id",
        "harvest_source_title",
        "harvest_source_organization",
        # --- Post-harvest enrichment scripts ---
        "encoding",
        "legal-constraints-reference-code",
        "metadata_created_source",
        "metadata_modified_source",
        "uri",
        "use-constraints-code",
    }
)

# Resource fields populated by CKAN's database layer or post-harvest scripts.
_RESOURCE_SKIP_FIELDS = frozenset(
    {
        # --- CKAN database records ---
        "cache_last_updated",
        "cache_url",
        "created",
        "datastore_active",
        "hash",
        "id",
        "last_modified",
        "metadata_modified",
        "mimetype",
        "mimetype_inner",
        "package_id",
        "position",
        "resource_type",
        "size",
        "state",
        "url_type",
        # --- Post-harvest enrichment scripts ---
        "created_source",
        "metadata_modified_source",
    }
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _json_default(obj):
    """Handle bytes returned by lxml when XPath hits element nodes."""
    if isinstance(obj, bytes):
        return obj.decode("utf-8", errors="replace")
    raise TypeError(f"Object of type {type(obj).__name__} is not JSON serializable")


def _normalise(value):
    """Round-trip through JSON to convert bytes → str."""
    return json.loads(json.dumps(value, default=_json_default))


def _normalise_extras(extras) -> dict:
    """Convert the extras field to a canonical sorted dict for comparison.

    Handles two forms:
    - ``list`` of ``{"key": k, "value": v}`` dicts — produced by the pipeline
    - ``dict`` — stored when a golden file was already normalised by this helper

    Production-only extras keys (harvest infrastructure, post-harvest scripts)
    are stripped via ``_EXTRAS_SKIP_KEYS``.  Python ``bool`` values are
    lowercased to match CKAN's DB round-trip (``True`` → ``"true"``).
    """
    if isinstance(extras, dict):
        items = extras.items()
    else:
        items = ((e["key"], e["value"]) for e in extras)

    result = {}
    for key, value in items:
        if key in _EXTRAS_SKIP_KEYS:
            continue
        if isinstance(value, bool):
            value = str(value).lower()
        result[key] = value
    return dict(sorted(result.items()))


def _filter_resource(resource: dict) -> dict:
    """Strip DB-generated and enrichment-service fields from a resource dict."""
    return {k: v for k, v in resource.items() if k not in _RESOURCE_SKIP_FIELDS}


def _filter(pkg: dict) -> dict:
    """Strip DB-generated and enrichment-service fields before comparison."""
    result = {k: v for k, v in pkg.items() if k not in _SKIP_FIELDS}
    if "extras" in result:
        result["extras"] = _normalise_extras(result["extras"])
    if "resources" in result:
        result["resources"] = [_filter_resource(r) for r in result["resources"]]
    return result


def _make_mock_harvest_object(guid: str) -> MagicMock:
    """Return a minimal mock HarvestObject that satisfies get_package_dict().

    Only the attributes actually read by SpatialHarvester / WAFHarvesterISO19115_3
    need to be set; everything else is covered by MagicMock auto-creation.
    """
    ho = MagicMock()
    ho.guid = guid
    ho.package = None
    ho.source.id = "00000000-0000-0000-0000-000000000001"
    ho.source.config = "{}"
    ho.source.title = "Test Harvest Source"
    ho.source.url = "http://test.example.com"
    ho.job.source.id = "00000000-0000-0000-0000-000000000001"
    ho.job.source.url = "http://test.example.com"
    ho.job.source.title = "Test Harvest Source"
    ho.job.id = "00000000-0000-0000-0000-000000000002"
    ho.id = "00000000-0000-0000-0000-000000000003"
    return ho


def _fixture_names():
    if not _XML_DIR.exists():
        return []
    return sorted(p.stem for p in _XML_DIR.glob("*.xml"))


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestISO19115_3:
    """Golden-file tests for the full XML → CKAN package dict pipeline.

    Each fixture XML is validated for correct root element, then run through
    the full pipeline and compared against a stored expected JSON.
    """

    @pytest.fixture(autouse=True)
    def setup_harvester(self):
        """Prepare a singleton harvester instance with an empty source config."""
        self.harvester = WAFHarvesterISO19115_3()
        self.harvester.config = {}

    # ------------------------------------------------------------------
    # Structural validation (no CKAN stack required)
    # ------------------------------------------------------------------

    @pytest.mark.parametrize("name", _fixture_names())
    def test_xml_root_element_is_mdb_md_metadata(self, name):
        """Every XML fixture must have ``mdb:MD_Metadata`` as its root element.

        The ISO 19115-3 harvester rejects anything that is not a proper
        ISO 19115-3 document (e.g. ISO 19139 ``gmd:MD_Metadata`` records).
        """
        xml_path = _XML_DIR / f"{name}.xml"
        tree = etree.fromstring(xml_path.read_bytes())
        expected_tag = f"{{{_MDB_NS}}}MD_Metadata"
        assert tree.tag == expected_tag, (
            f"'{name}.xml' has root element <{tree.tag}>, "
            f"expected <{{{{{_MDB_NS}}}}}MD_Metadata>.  "
            "This harvester only accepts ISO 19115-3 documents."
        )

    # ------------------------------------------------------------------
    # Full pipeline golden-file test (requires CKAN stack via app fixture)
    # ------------------------------------------------------------------

    @pytest.mark.parametrize("name", _fixture_names())
    def test_package_dict_matches_expected(self, request, name, app):
        """Parse an XML fixture, build the package dict, compare to expected JSON.

        The ``app`` fixture (provided by pytest-ckan) ensures the full CKAN
        plugin stack — scheming, fluent, composite — is initialised so that
        ``get_package_dict()`` can resolve the dataset schema and language list.

        Missing JSON
        ~~~~~~~~~~~~
        If no JSON file exists for *name*, the current pipeline output (after
        field filtering) is written as the new expected file and the test is
        skipped.  Review then re-run.

        Regenerating
        ~~~~~~~~~~~~
        Pass ``--regenerate-fixtures`` to overwrite all package JSON files.
        """
        xml_path = _XML_DIR / f"{name}.xml"
        json_path = _JSON_DIR / f"{name}.json"

        regenerate = request.config.getoption("--regenerate-fixtures", default=False)

        # --- Step 1: parse XML ---
        xml_bytes = xml_path.read_bytes()
        iso_values = ISODocument(xml_bytes).read_values()
        guid = iso_values.get("guid", "unknown-guid")
        mock_ho = _make_mock_harvest_object(guid)

        # --- Step 2: build package dict ---
        mock_source_pkg = MagicMock()
        mock_source_pkg.owner_org = None

        with (
            patch("ckan.model.Package.get", return_value=mock_source_pkg),
            patch.object(
                self.harvester,
                "_save_object_error",
                side_effect=lambda msg, *a, **kw: log.warning("harvest error: %s", msg),
            ),
        ):
            package_dict = self.harvester.get_package_dict(iso_values, mock_ho)

        result = _filter(_normalise(package_dict))

        # --- Generate golden file if missing or regeneration requested ---
        if not json_path.exists() or regenerate:
            _JSON_DIR.mkdir(parents=True, exist_ok=True)
            json_path.write_text(
                json.dumps(result, indent=2, sort_keys=True, ensure_ascii=False),
                encoding="utf-8",
            )
            action = "Regenerated" if regenerate else "Generated"
            pytest.skip(
                f"{action} expected package JSON for '{name}' → "
                f"tests/fixtures/iso19115_3/01-ckan-package/{name}.json  "
                "Review the file and re-run to validate."
            )

        # --- Compare ---
        expected_raw = json.loads(json_path.read_text(encoding="utf-8"))
        expected = _filter(expected_raw)

        assert result == expected, (
            f"Package dict for '{name}' does not match expected JSON.\n"
            f"  Expected : {json_path}\n"
            f"  To regenerate all fixtures: pytest --regenerate-fixtures"
        )
