"""Level 2 — CKAN package dict tests for the ISO 19115-3 harvester.

Tests the full transformation from XML to a CKAN-ready package dict:

    XML
    → ISODocument_iso19115_3.read_values()      (Level 1, parser/)
    → WAFHarvesterCIOOS.get_package_dict()       (Level 2, package/)

This exercises scheming / fluent / composite field handling, resource
building, extras flattening, and all CIOOS-specific post-processing that
runs in ``get_package_dict()``.

Fixture files
-------------
- ``tests/fixtures/iso19115_3/00-xml/<name>.xml``           — input XML (shared with Level 1)
- ``tests/fixtures/iso19115_3/02-ckan-package/<name>.json``  — expected package dict

The expected JSON may be a raw production ``package_show`` API response.
Fields that are generated by CKAN's database layer or by post-harvest
enrichment services (translation, registry lookups) are stripped before
comparison using ``_SKIP_FIELDS``.

Workflow
--------
1. Add matching XML + JSON pairs (XML is shared with Level 1).
2. Run ``pytest`` — if no package JSON exists, one is generated from the
   current pipeline output and the test is skipped.
3. Review/edit the generated JSON in ``package/<name>.json``.
4. Re-run — test now asserts pipeline output == stored JSON.

Regenerate all golden files after intentional pipeline changes::

    pytest --regenerate-fixtures
"""

import json
import logging
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from ckanext.cioos_harvest.harvesters.waf_iso19115_3 import WAFHarvesterISO19115_3
from ckanext.cioos_harvest.model.harvested_metadata_iso19115_3 import (
    ISODocument_iso19115_3,
)

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_TESTS_DIR = Path(__file__).parent
_FIXTURES_DIR = _TESTS_DIR / "fixtures" / "iso19115_3"
_XML_DIR = _FIXTURES_DIR / "00-xml"
_JSON_DIR = _FIXTURES_DIR / "02-ckan-package"

# ---------------------------------------------------------------------------
# Fields excluded from comparison
# ---------------------------------------------------------------------------

# These fields appear in production package_show responses but are created by
# CKAN's database layer or by post-harvest enrichment services, never by the
# XML parsing + package-dict transformation that we are testing here.
_SKIP_FIELDS = frozenset(
    {
        # --- CKAN database records ---
        "id",
        "name",
        "creator_user_id",
        "metadata_created",
        "metadata_modified",
        "num_resources",
        "num_tags",
        "isopen",
        "license_id",
        "license_title",
        "resources",  # full resource dicts with DB-assigned IDs / timestamps
        "groups",  # DB-resolved group records
        "organization",  # DB-resolved organization record
        "owner_org",
        "state",
        "type",
        "private",
        "relationships_as_object",
        "relationships_as_subject",
        # --- Post-harvest enrichment (translation service, CIOOS registry) ---
        "harvest_document_content",
        "xml_location_url",
        "included_in_data_catalogue",
        "citation",
        "notes_translated",
        "title_translated",
        "keywords_translation_method",
        "notes_translation_method",
        "title_translation_method",
        # --- Fields populated by CIOOS post-harvest scripts, not the parser ---
        "eov",
        "ecv",
        "datacentre",
        "projects",
        # --- Standard CKAN author / maintainer (not mapped from ISO 19115-3) ---
        "author",
        "author_email",
        "maintainer",
        "maintainer_email",
        "url",
    }
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _json_default(obj):
    """Handle bytes returned by lxml when XPath hits element nodes."""
    if isinstance(obj, bytes):
        return obj.decode("utf-8", errors="replace")
    raise TypeError(f"Object of type {type(obj).__name__} is not JSON serializable")


def _normalise(value):
    """Round-trip through JSON to convert bytes → str."""
    return json.loads(json.dumps(value, default=_json_default))


def _filter(pkg: dict) -> dict:
    """Strip DB-generated and enrichment-service fields before comparison."""
    return {k: v for k, v in pkg.items() if k not in _SKIP_FIELDS}


def _make_mock_harvest_object(guid: str) -> MagicMock:
    """Return a minimal mock HarvestObject that satisfies get_package_dict().

    Only the attributes actually read by SpatialHarvester / WAFHarvesterCIOOS
    need to be set; everything else is covered by MagicMock auto-creation.
    """
    ho = MagicMock()
    ho.guid = guid
    ho.package = None  # new record — not updating an existing package
    # HarvestSource attributes
    ho.source.id = "00000000-0000-0000-0000-000000000001"
    ho.source.config = "{}"
    ho.source.title = "Test Harvest Source"
    ho.source.url = "http://test.example.com"
    # HarvestJob attributes (used for default_extras template substitution)
    ho.job.source.id = "00000000-0000-0000-0000-000000000001"
    ho.job.source.url = "http://test.example.com"
    ho.job.source.title = "Test Harvest Source"
    ho.job.id = "00000000-0000-0000-0000-000000000002"
    ho.id = "00000000-0000-0000-0000-000000000003"
    return ho


def _fixture_names():
    if not _XML_DIR.exists():
        return []
    return sorted(p.stem for p in _XML_DIR.glob("*.xml"))


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestISO19115_3PackageDict:
    """Golden-file tests for the full XML → CKAN package dict pipeline.

    Each test:
    1. Parses the XML with ``ISODocument_iso19115_3.read_values()``.
    2. Passes the result to ``WAFHarvesterCIOOS.get_package_dict()``
       (with the minimum DB calls mocked out).
    3. Strips ``_SKIP_FIELDS`` from both sides.
    4. Compares against the stored expected JSON.
    """

    @pytest.fixture(autouse=True)
    def setup_harvester(self):
        """Prepare a singleton harvester instance with an empty source config."""
        self.harvester = WAFHarvesterISO19115_3()
        # config is normally set by import_stage(); set it explicitly so that
        # source_config (used by handle_fluent_harvest_dictinary etc.) returns {}.
        self.harvester.config = {}

    @pytest.mark.parametrize("name", _fixture_names())
    def test_package_dict_matches_expected(self, request, name, app):
        """Parse an XML fixture, build the package dict, compare to expected JSON.

        The ``app`` fixture (provided by pytest-ckan) ensures the full CKAN
        plugin stack — scheming, fluent, composite — is initialised so that
        ``get_package_dict()`` can resolve the dataset schema and language list.

        Missing JSON
        ~~~~~~~~~~~~
        If no JSON file exists for *name*, the current pipeline output (after
        field filtering) is written as the new expected file and the test is
        skipped.  Review then re-run.

        Regenerating
        ~~~~~~~~~~~~
        Pass ``--regenerate-fixtures`` to overwrite all package JSON files.
        """
        xml_path = _XML_DIR / f"{name}.xml"
        json_path = _JSON_DIR / f"{name}.json"

        regenerate = request.config.getoption("--regenerate-fixtures", default=False)

        # --- Step 1: parse XML ---
        xml_bytes = xml_path.read_bytes()
        iso_values = ISODocument_iso19115_3(xml_bytes).read_values()
        guid = iso_values.get("guid", "unknown-guid")
        mock_ho = _make_mock_harvest_object(guid)

        # --- Step 2: build package dict ---
        # Mock the one DB-dependent call in SpatialHarvester.get_package_dict():
        #   model.Package.get(harvest_object.source.id)
        # This looks up the HarvestSource as a CKAN Package to read owner_org.
        # We return a mock with owner_org=None (no organisation assigned).
        mock_source_pkg = MagicMock()
        mock_source_pkg.owner_org = None

        with (
            patch("ckan.model.Package.get", return_value=mock_source_pkg),
            patch.object(
                self.harvester,
                "_save_object_error",
                side_effect=lambda msg, *a, **kw: log.warning("harvest error: %s", msg),
            ),
        ):
            package_dict = self.harvester.get_package_dict(iso_values, mock_ho)

        result = _filter(_normalise(package_dict))

        # --- Generate golden file if missing or regeneration requested ---
        if not json_path.exists() or regenerate:
            _JSON_DIR.mkdir(parents=True, exist_ok=True)
            json_path.write_text(
                json.dumps(result, indent=2, sort_keys=True, ensure_ascii=False),
                encoding="utf-8",
            )
            action = "Regenerated" if regenerate else "Generated"
            pytest.skip(
                f"{action} expected package JSON for '{name}' → "
                f"tests/fixtures/iso19115_3/02-ckan-package/{name}.json  "
                "Review the file and re-run to validate."
            )

        # --- Compare ---
        expected_raw = json.loads(json_path.read_text(encoding="utf-8"))
        expected = _filter(expected_raw)

        assert result == expected, (
            f"Package dict for '{name}' does not match expected JSON.\n"
            f"  Expected : {json_path}\n"
            f"  To regenerate all fixtures: pytest --regenerate-fixtures"
        )
