# This is a basic workflow that is manually triggered

name: Build ckan on pull request

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_DISPATCH_ACCESS_TOKEN }}
        repository: cioos-siooc/ckan
        event-type: submodule-pull-request
        client-payload: '{"submodule": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "head_ref":"${{ github.event.pull_request.head.ref }}", "head_sha":"${{ github.event.pull_request.head.sha }}", "base_ref":"${{ github.event.pull_request.base.ref }}", "base_sha":"${{ github.event.pull_request.base.sha }}", "prn":"${{ github.event.pull_request.number}}"}'
    - name: print event
      run: echo "${{ toJson(github.event) }}"
